name: Deploy Sentiment Analyzer
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies (Client)
        run: |
          cd client
          npm install
          npm run build
      - name: Install Dependencies (Server)
        run: |
          cd server
          npm install
      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

        run: |
          cd server
          npx wrangler deploy
      - name: Deploy Pages
        env:
            CLOUDFLARE_API_TOKEN: ${{ secret_API_TOKEN }}
            GITHUB_ACCESS_TOKEN: ${{ secret_ACCESS_TOKEN }}
        run: |
          cd client
          npx wrangler pages deploy dist --project-name=sentiment-analyzer